### ISSUE TITLE
Handshake failed [pre-Lollipop/Kitkat Watch]

### ISSUE THREAD

**Issue by BluRaf** [Vavassor/Tusky#221]
Unlike #46, this problem is appearing because TLS 1.1 and TLS 1.2 isn't enabled by default in Android from version 4.1.x (API level 16) to 4.4.x (API level 19).

The solution is to manually enable new TLS versions by creating custom [SSLSocketFactory](https://developer.android.com/reference/javax/net/ssl/SSLSocketFactory.html) and proxy all calls through it; 
more details are available on this page: https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/

```
W/System.err( 5228): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x513b4400: Failure in SSL library, usually a protocol error
W/System.err( 5228): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x40c6b87e:0x00000000)
W/System.err( 5228): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:412)
W/System.err( 5228): 	at a.a.b.c.a(RealConnection.java:267)
W/System.err( 5228): 	at a.a.b.c.a(RealConnection.java:11237)
W/System.err( 5228): 	at a.a.b.g.a(StreamAllocation.java:186)
W/System.err( 5228): 	at a.a.b.g.a(StreamAllocation.java:121)
W/System.err( 5228): 	at a.a.b.g.a(StreamAllocation.java:100)
W/System.err( 5228): 	at a.a.b.a.a(ConnectInterceptor.java:42)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:92)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:67)
W/System.err( 5228): 	at a.a.a.a.a(CacheInterceptor.java:93)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:92)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:67)
W/System.err( 5228): 	at a.a.c.a.a(BridgeInterceptor.java:93)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:92)
W/System.err( 5228): 	at a.a.c.j.a(RetryAndFollowUpInterceptor.java:120)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:92)
W/System.err( 5228): 	at a.a.c.g.a(RealInterceptorChain.java:67)
W/System.err( 5228): 	at a.y.f(RealCall.java:179)
W/System.err( 5228): 	at a.y$a.b(RealCall.java:129)
W/System.err( 5228): 	at a.a.b.run(NamedRunnable.java:32)
W/System.err( 5228): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/System.err( 5228): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/System.err( 5228): 	at java.lang.Thread.run(Thread.java:856)
W/System.err( 5228): 	Suppressed: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x513b4808: Failure in SSL library, usually a protocol error
W/System.err( 5228): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x40c6b87e:0x00000000)
W/System.err( 5228): 		... 23 more
W/System.err( 5228): 	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x513b4808: Failure in SSL library, usually a protocol error
W/System.err( 5228): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x40c6b87e:0x00000000)
W/System.err( 5228): 		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err( 5228): 		at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
W/System.err( 5228): 		... 22 more
W/System.err( 5228): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x513b4400: Failure in SSL library, usually a protocol error
W/System.err( 5228): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x40c6b87e:0x00000000)
W/System.err( 5228): 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err( 5228): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
W/System.err( 5228): 	... 22 more
```

**Comment by Vavassor** [comment]
That fix is already present. All the client objects that are built on pre-Lollipop enable TLS 1.1 and 1.2 with this code: https://github.com/Vavassor/Tusky/blob/master/app/src/main/java/com/keylesspalace/tusky/OkHttpUtils.java#L149

I'm not positive the cause of your issue. But, hazarding a guess I'd say it's either some cipher suites not being supported on that android version, or being supported but not the particular settings used by the server?

**Comment by BluRaf** [comment]
I haven't noticed that function, I'm sorry.
I'll analyse cipher suites problem more and report the results in #46.
