### ISSUE TITLE
IndexOutOfBoundsException in ViewThreadFragment.java:1080

### ISSUE THREAD

**Issue by MightyPork** [Vavassor/Tusky#325]
caught one of the crashes, here's it's trace for future reference

```
07-02 07:27:11.860 32662 32662 E AndroidRuntime: FATAL EXCEPTION: main
07-02 07:27:11.860 32662 32662 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 32662
07-02 07:27:11.860 32662 32662 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:411)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at com.keylesspalace.tusky.aq$1.onResponse(ViewThreadFragment.java:1080)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6126)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-02 07:27:11.860 32662 32662 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

latest from play store

I've also seen this with index: 4, size: 4

edit: just checked and it happens when you tap some toots (probably not too helpful, as iirc all the crashes have this trigger)

edit 2: from AndroidStudio on the release tag

```
07-02 21:58:54.998 18297 18297 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:411)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at com.keylesspalace.tusky.ThreadAdapter.setStatus(ThreadAdapter.java:80)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at com.keylesspalace.tusky.ViewThreadFragment$1.onResponse(ViewThreadFragment.java:106)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6126)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-02 21:58:54.998 18297 18297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-02 21:58:55.000   776   807 W ActivityManager:   Force finishing activity com.keylesspalace.tusky/.ViewThreadActivity
```

I'll try if I can reproduce this on master

**Comment by Vavassor** [comment]
This crash is unfortunately pretty common in the current play store version. It was fixed in commit 8b4e377d3411c8d42bd32961f51004cab0d5a1a1 but hasn't been released yet.

**Comment by MightyPork** [comment]
I think you're right, I can't reproduce it on master. But the toots that used to crash it now (a) take long to load - which is OK, or (b) twice quickly flash. I think sensitive people will have beef with that

**Comment by Vavassor** [comment]
Oh? I haven't noticed that, could you link an example post?

**Comment by MightyPork** [comment]
I'll make a new issue for it to keep it on topic
